# Generated by Django 5.0.6 on 2024-06-27 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
